version: '3.8'

services:
  actions-bridge:
    build: .
    image: confighub/actions-bridge:latest
    container_name: actions-bridge
    restart: unless-stopped
    environment:
      # ConfigHub connection settings
      CONFIGHUB_WORKER_ID: ${CONFIGHUB_WORKER_ID}
      CONFIGHUB_WORKER_SECRET: ${CONFIGHUB_WORKER_SECRET}
      CONFIGHUB_URL: ${CONFIGHUB_URL:-https://api.confighub.com}
      
      # Bridge configuration
      ACTIONS_BRIDGE_BASE_DIR: /var/lib/actions-bridge
      MAX_CONCURRENT_WORKFLOWS: ${MAX_CONCURRENT_WORKFLOWS:-5}
      
      # Act configuration
      ACT_DEFAULT_IMAGE: catthehacker/ubuntu:act-22.04
      ACT_PLATFORM: linux/amd64
      
      # Health check
      HEALTH_ADDR: :8080
      
      # Debug mode
      DEBUG: ${DEBUG:-false}
    
    ports:
      - "8080:8080"  # Health check and metrics
    
    volumes:
      # Docker socket for act
      - /var/run/docker.sock:/var/run/docker.sock
      # Persistent storage for workspaces
      - actions-bridge-data:/var/lib/actions-bridge
      # Optional: Mount local workflows for testing
      # - ./test/fixtures/workflows:/workflows:ro
    
    networks:
      - actions-bridge-net
    
    # Required for act to work properly
    security_opt:
      - apparmor:unconfined
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Optional: Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: actions-bridge-prometheus
    restart: unless-stopped
    profiles:
      - monitoring
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    networks:
      - actions-bridge-net

volumes:
  actions-bridge-data:
    driver: local
  prometheus-data:
    driver: local

networks:
  actions-bridge-net:
    driver: bridge