apiVersion: actions.confighub.com/v1alpha1
kind: Actions
metadata:
  name: test-minimal
name: Minimal Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test"