apiVersion: actions.confighub.com/v1alpha1
kind: Actions
metadata:
  name: file-persistence-local
name: File Persistence (Local Only)
on: 
  workflow_dispatch:

env:
  CONFIG_DIR: /tmp/confighub-persist/example

jobs:
  setup-and-persist:
    runs-on: ubuntu-latest
    
    steps:
      - name: Initialize persistence system
        run: |
          # Create persistent directory structure
          mkdir -p "$CONFIG_DIR"/{current,history,artifacts}
          
          # Create persistence marker
          cat > "$CONFIG_DIR/.persistence" << EOF
          {
            "initialized": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "base_dir": "$CONFIG_DIR",
            "version": "1.0"
          }
          EOF
          
          echo "✓ Persistence system initialized"
          echo "Configuration directory: $CONFIG_DIR"

      - name: Generate configuration
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          REVISION="$(date +%s)"
          
          # Create revision directory
          REV_DIR="$CONFIG_DIR/history/r${REVISION}"
          mkdir -p "$REV_DIR"
          
          # Generate metadata
          cat > "$REV_DIR/metadata.json" << EOF
          {
            "environment": "local",
            "revision": ${REVISION},
            "timestamp": "$TIMESTAMP"
          }
          EOF
          
          # Generate main configuration
          cat > "$REV_DIR/config.yaml" << EOF
          # Configuration Example
          # Generated: $TIMESTAMP
          # Revision: $REVISION
          
          application:
            name: example-app
            environment: local
            version: "1.0.${REVISION}"
            
          features:
            logging:
              level: debug
              format: json
            
            database:
              host: localhost
              port: 5432
              ssl: false
          EOF
          
          # Copy to current
          cp -r "$REV_DIR"/* "$CONFIG_DIR/current/"
          
          echo "✓ Configuration generated (revision: $REVISION)"

      - name: Create deployment artifacts
        run: |
          # Create Kubernetes manifest
          cat > "$CONFIG_DIR/artifacts/deployment.yaml" << EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: example-app
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: example-app
            template:
              metadata:
                labels:
                  app: example-app
              spec:
                containers:
                - name: app
                  image: example-app:latest
          EOF
          
          echo "✓ Deployment artifacts created"

      - name: Validate persistence
        run: |
          echo "==============================" 
          echo "PERSISTENCE VALIDATION"
          echo "==============================" 
          echo ""
          echo "Checking persisted structure..."
          
          # Validate directory structure
          for dir in current history artifacts; do
            if [ -d "$CONFIG_DIR/$dir" ]; then
              echo "✓ $dir directory exists"
            else
              echo "✗ $dir directory missing"
              exit 1
            fi
          done
          
          # List persisted files
          echo ""
          echo "Persisted files:"
          find "$CONFIG_DIR" -type f -name "*.yaml" -o -name "*.json" | while read file; do
            echo "- ${file#$CONFIG_DIR/}"
          done
          
          echo ""
          echo "✓ Validation successful"

      - name: Demonstrate retrieval
        run: |
          echo "==============================" 
          echo "CONFIGURATION RETRIEVAL DEMO"
          echo "==============================" 
          echo ""
          
          # Show current configuration
          echo "Current configuration:"
          if [ -f "$CONFIG_DIR/current/config.yaml" ]; then
            cat "$CONFIG_DIR/current/config.yaml"
          fi
          
          echo ""
          echo "✓ Configuration retrieval successful"

      - name: Summary
        run: |
          echo "==============================" 
          echo "FILE PERSISTENCE SUMMARY"
          echo "==============================" 
          echo ""
          echo "This example demonstrates:"
          echo "- Local file persistence in /tmp"
          echo "- Configuration versioning with history"
          echo "- Artifact generation from configs"
          echo "- Retrieval and usage patterns"
          echo ""
          echo "Key features:"
          echo "- Simple single-job workflow"
          echo "- No dependency on GitHub features" 
          echo "- Works reliably with act"
          echo "- All operations in one job"
          echo ""
          echo "Files persist at: $CONFIG_DIR"
          echo "==============================" 