name: GitOps Preview
on:
  workflow_dispatch:
    inputs:
      source-space:
        description: 'Source ConfigHub space'
        required: true
        type: choice
        options:
          - development
          - staging
      target-space:
        description: 'Target ConfigHub space'
        required: true
        type: choice
        options:
          - staging
          - production
      dry-run:
        description: 'Preview only (no actual changes)'
        type: boolean
        default: true

jobs:
  fetch-configurations:
    runs-on: ubuntu-latest
    outputs:
      source-configs: ${{ steps.source.outputs.configs }}
      target-configs: ${{ steps.target.outputs.configs }}
    
    steps:
      - name: Fetch source space configs
        id: source
        run: |
          echo "Fetching configurations from ${{ github.event.inputs.source-space }}..."
          
          # Simulate ConfigHub config fetch
          if [ "${{ github.event.inputs.source-space }}" = "development" ]; then
            CONFIGS='[
              {"unit":"webapp","version":"2.1.0-dev","replicas":2},
              {"unit":"api","version":"3.0.0-dev","replicas":2},
              {"unit":"worker","version":"1.5.0-dev","replicas":1}
            ]'
          else
            CONFIGS='[
              {"unit":"webapp","version":"2.0.0","replicas":3},
              {"unit":"api","version":"2.9.0","replicas":3},
              {"unit":"worker","version":"1.4.0","replicas":2}
            ]'
          fi
          
          echo "configs=$CONFIGS" >> $GITHUB_OUTPUT
          echo "âœ“ Found $(echo $CONFIGS | jq length) configurations"
      
      - name: Fetch target space configs
        id: target
        run: |
          echo "Fetching configurations from ${{ github.event.inputs.target-space }}..."
          
          # Simulate target space configs
          if [ "${{ github.event.inputs.target-space }}" = "production" ]; then
            CONFIGS='[
              {"unit":"webapp","version":"1.9.0","replicas":5},
              {"unit":"api","version":"2.8.0","replicas":5},
              {"unit":"worker","version":"1.3.0","replicas":3}
            ]'
          else
            CONFIGS='[
              {"unit":"webapp","version":"2.0.0","replicas":3},
              {"unit":"api","version":"2.9.0","replicas":3},
              {"unit":"worker","version":"1.4.0","replicas":2}
            ]'
          fi
          
          echo "configs=$CONFIGS" >> $GITHUB_OUTPUT
          echo "âœ“ Found $(echo $CONFIGS | jq length) configurations"

  analyze-changes:
    runs-on: ubuntu-latest
    needs: fetch-configurations
    outputs:
      has-changes: ${{ steps.diff.outputs.has_changes }}
      change-summary: ${{ steps.diff.outputs.summary }}
    
    steps:
      - name: Compare configurations
        id: diff
        run: |
          echo "========================================"
          echo "GITOPS CHANGE ANALYSIS"
          echo "========================================"
          echo "Source: ${{ github.event.inputs.source-space }}"
          echo "Target: ${{ github.event.inputs.target-space }}"
          echo ""
          
          SOURCE='${{ needs.fetch-configurations.outputs.source-configs }}'
          TARGET='${{ needs.fetch-configurations.outputs.target-configs }}'
          
          echo "Changes to be synchronized:"
          echo ""
          
          # Compare each unit
          CHANGES=0
          for unit in webapp api worker; do
            SOURCE_VER=$(echo "$SOURCE" | jq -r ".[] | select(.unit==\"$unit\") | .version")
            TARGET_VER=$(echo "$TARGET" | jq -r ".[] | select(.unit==\"$unit\") | .version")
            SOURCE_REP=$(echo "$SOURCE" | jq -r ".[] | select(.unit==\"$unit\") | .replicas")
            TARGET_REP=$(echo "$TARGET" | jq -r ".[] | select(.unit==\"$unit\") | .replicas")
            
            if [ "$SOURCE_VER" != "$TARGET_VER" ] || [ "$SOURCE_REP" != "$TARGET_REP" ]; then
              echo "ðŸ“¦ $unit:"
              [ "$SOURCE_VER" != "$TARGET_VER" ] && echo "   Version: $TARGET_VER â†’ $SOURCE_VER"
              [ "$SOURCE_REP" != "$TARGET_REP" ] && echo "   Replicas: $TARGET_REP â†’ $SOURCE_REP"
              CHANGES=$((CHANGES + 1))
            fi
          done
          
          if [ $CHANGES -eq 0 ]; then
            echo "âœ“ No changes detected - spaces are in sync"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo ""
            echo "Total changes: $CHANGES"
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "summary=$CHANGES units will be updated" >> $GITHUB_OUTPUT
          fi

  validate-changes:
    runs-on: ubuntu-latest
    needs: analyze-changes
    if: needs.analyze-changes.outputs.has-changes == 'true'
    
    steps:
      - name: Validate proposed changes
        run: |
          echo "Validating proposed GitOps changes..."
          echo ""
          
          # Simulate validation checks
          echo "Running validation checks:"
          echo "âœ“ Schema validation passed"
          echo "âœ“ Resource limits checked"
          echo "âœ“ Dependency compatibility verified"
          echo "âœ“ Security policies satisfied"
          
          # Check for risky changes
          if [ "${{ github.event.inputs.target-space }}" = "production" ]; then
            echo ""
            echo "âš ï¸  Production deployment checks:"
            echo "âœ“ Backup strategy confirmed"
            echo "âœ“ Rollback plan available"
            echo "âœ“ Maintenance window compatible"
            echo "âœ“ SLA requirements met"
          fi

  generate-plan:
    runs-on: ubuntu-latest
    needs: [fetch-configurations, analyze-changes, validate-changes]
    if: needs.analyze-changes.outputs.has-changes == 'true'
    
    steps:
      - name: Generate deployment plan
        run: |
          echo "========================================"
          echo "GITOPS DEPLOYMENT PLAN"
          echo "========================================"
          echo ""
          echo "This plan will synchronize:"
          echo "${{ github.event.inputs.source-space }} â†’ ${{ github.event.inputs.target-space }}"
          echo ""
          echo "Execution Order:"
          echo "1. Pre-deployment health checks"
          echo "2. Create configuration backups"
          echo "3. Apply configuration changes:"
          
          SOURCE='${{ needs.fetch-configurations.outputs.source-configs }}'
          
          # Show deployment order
          echo "$SOURCE" | jq -r '.[] | "   - \(.unit): v\(.version) (\(.replicas) replicas)"'
          
          echo "4. Rolling deployment with health checks"
          echo "5. Post-deployment validation"
          echo "6. Update GitOps state tracking"
          echo ""
          echo "Estimated Duration: 15-20 minutes"
          echo "Rollback Strategy: Automated on failure"

  apply-changes:
    runs-on: ubuntu-latest
    needs: [analyze-changes, generate-plan]
    if: |
      needs.analyze-changes.outputs.has-changes == 'true' &&
      github.event.inputs.dry-run != 'true'
    
    steps:
      - name: Apply GitOps changes
        run: |
          echo "========================================"
          echo "APPLYING GITOPS CHANGES"
          echo "========================================"
          echo ""
          echo "ðŸš€ Starting GitOps synchronization..."
          echo ""
          
          # Simulate applying changes
          for unit in webapp api worker; do
            echo "Updating $unit..."
            echo "  - Fetching configuration from source"
            echo "  - Applying to target space"
            echo "  - Waiting for rollout..."
            sleep 2
            echo "  âœ“ $unit updated successfully"
            echo ""
          done
          
          echo "âœ“ All changes applied successfully!"
          echo ""
          echo "Post-deployment tasks:"
          echo "âœ“ Metrics dashboards updated"
          echo "âœ“ Alerts reconfigured"
          echo "âœ“ Audit trail recorded"

  preview-only:
    runs-on: ubuntu-latest
    needs: [analyze-changes, generate-plan]
    if: github.event.inputs.dry-run == 'true'
    
    steps:
      - name: Show preview summary
        run: |
          echo "========================================"
          echo "GITOPS PREVIEW MODE"
          echo "========================================"
          echo ""
          echo "This is a DRY RUN - no changes will be made"
          echo ""
          echo "Summary of changes that would be applied:"
          echo "- Source: ${{ github.event.inputs.source-space }}"
          echo "- Target: ${{ github.event.inputs.target-space }}"
          echo "- Changes: ${{ needs.analyze-changes.outputs.change-summary }}"
          echo ""
          echo "To apply these changes, run again with dry-run=false"

  record-state:
    runs-on: ubuntu-latest
    needs: [apply-changes]
    if: always() && needs.apply-changes.result == 'success'
    
    steps:
      - name: Update GitOps state
        run: |
          echo "Recording GitOps state..."
          
          cat > gitops-state.json << EOF
          {
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "sync": {
              "from": "${{ github.event.inputs.source-space }}",
              "to": "${{ github.event.inputs.target-space }}"
            },
            "workflow_run": "${{ github.run_id }}",
            "triggered_by": "${{ github.actor }}",
            "changes_applied": true,
            "state": "synchronized",
            "next_sync": "$(date -u -d '+1 hour' +%Y-%m-%dT%H:%M:%SZ)"
          }
          EOF
          
          echo "GitOps state recorded:"
          cat gitops-state.json | jq .
          echo ""
          echo "âœ“ State tracking updated in ConfigHub" 